### ISSUE TITLE
Generalize reading itp files

### ISSUE THREAD

**Issue by mattwthompson** [mattwthompson/mtools#3]
Currently itp files are read in with the assumption that the file name is the same as the resname, which will fail for water, and most code written by others, molecules with multiple abbreviations, e.g.

```
emim, NULL = read_charges('../../forcefields/emim.itp')
tfsi, NULL = read_charges('../../forcefields/Tf2N.itp')
charges = dict(emim, **tfsi)
```

This may require reading the topology file.

**Comment by ctk3b** [comment]
ParmEd can read these. Shouldn't be too hard to extract the info you want.

**Comment by mattwthompson** [comment]
Didn't see this until now. Thanks, I'll have a look.

**Comment by mattwthompson** [comment]
Added with 8272078929ee93f4ec773be8eb2096c33d15cea4 (despite bad commit message).
