### ISSUE TITLE
PBC accounting in pairing module

### ISSUE THREAD

**Issue by mattwthompson** [mattwthompson/mtools#7]
From what I can tell, PBC are currently not respected. 

https://github.com/mattwthompson/mtools/blob/master/mtools/pairing.py#L74

**Comment by ctk3b** [comment]
Could you express the distance part of that calculation using `mdtraj.compute_distances`?

**Comment by mattwthompson** [comment]
Figure that's the best approach. We'll see!

**Comment by ctk3b** [comment]
Or if you want the crappy version: https://github.com/ctk3b/groupy/blob/master/groupy/general.py#L110

**Comment by mattwthompson** [comment]
The results are certainly different....

![image](https://user-images.githubusercontent.com/7935382/40207011-fc838e7e-59f7-11e8-8c86-d6b8bdff7536.png)

**Comment by mattwthompson** [comment]
And with `periodic=False` in `mdtraj.compute_distances`

![image](https://user-images.githubusercontent.com/7935382/40207167-bb2586ca-59f8-11e8-87d0-f0e4717713e9.png)
🤔

**Comment by mattwthompson** [comment]
![image](https://user-images.githubusercontent.com/7935382/40246512-9e80b5d0-5a8e-11e8-9179-4d457b3ef1e1.png)

Came down to an embarrassing typo. The distance formula is the sqrt of the sum of squares, but I was summing up the square root of squares. The fixed typo produces the same results as `periodic=False` using `mdtraj.compute_distances`.

**Comment by ctk3b** [comment]
> The fixed typo produces the same results as periodic=False using mdtraj.compute_distances

Noice ✊

**Comment by mattwthompson** [comment]
Closed 1b77dfa29fbc9f7a726ae1d5a114da6b1c206e65 74b9f1218d0181eb246a8c5b30f11cae82eb6831
